import * as fs from 'fs';
import * as path from 'path';
import { randomUUID } from 'crypto';
import { getHydraHome } from './path';

export interface CompletionHookScriptIdentity {
  workerId: number;
  lifecycleEpoch: string;
  agentType: string;
}

export function getCompletionHookScriptPath(
  workerId: number,
  platform: typeof process.platform = process.platform,
): string {
  validateIdentity({ workerId, lifecycleEpoch: 'path-validation', agentType: 'path-validation' });
  return path.join(getHydraHome(), 'hooks', `completion-worker-${workerId}.${scriptExtension(platform)}`);
}

export function getLegacyCompletionHookScriptPath(
  sessionName: string,
  platform: typeof process.platform = process.platform,
): string | undefined {
  const normalized = sessionName.trim();
  if (!normalized || normalized.includes('/') || normalized.includes('\\') || normalized.includes('\0')) {
    return undefined;
  }
  return path.join(getHydraHome(), 'hooks', `notify-${normalized}.${scriptExtension(platform)}`);
}

export function buildCompletionHookScript(
  identity: CompletionHookScriptIdentity,
  platform: typeof process.platform = process.platform,
): string {
  validateIdentity(identity);
  return platform === 'win32'
    ? buildPowerShellScript(identity)
    : buildPosixScript(identity);
}

export function writeCompletionHookScript(
  scriptPath: string,
  identity: CompletionHookScriptIdentity,
  platform: typeof process.platform = process.platform,
): boolean {
  const content = buildCompletionHookScript(identity, platform);
  const existing = readFile(scriptPath);
  if (existing === content) {
    if (platform !== 'win32') fs.chmodSync(scriptPath, 0o755);
    return false;
  }
  fs.mkdirSync(path.dirname(scriptPath), { recursive: true });
  const tmpPath = path.join(
    path.dirname(scriptPath),
    `${path.basename(scriptPath)}.${process.pid}.${Date.now()}.${randomUUID()}.tmp`,
  );
  fs.writeFileSync(tmpPath, content, 'utf-8');
  if (platform !== 'win32') fs.chmodSync(tmpPath, 0o755);
  fs.renameSync(tmpPath, scriptPath);
  return true;
}

export function refreshCompletionHookScripts(
  sessionName: string,
  identity: CompletionHookScriptIdentity,
  platform: typeof process.platform = process.platform,
): string[] {
  const paths = [getCompletionHookScriptPath(identity.workerId, platform)];
  const legacyPath = getLegacyCompletionHookScriptPath(sessionName, platform);
  if (legacyPath && !paths.includes(legacyPath)) paths.push(legacyPath);
  for (const scriptPath of paths) {
    writeCompletionHookScript(scriptPath, identity, platform);
  }
  return paths;
}

function buildPosixScript(identity: CompletionHookScriptIdentity): string {
  const sq = (value: string) => `'${value.replace(/'/g, "'\\''")}'`;
  return [
    '#!/bin/sh',
    '# Auto-generated by Hydra: structured worker completion signal.',
    '',
    `WORKER_ID=${sq(String(identity.workerId))}`,
    `LIFECYCLE_EPOCH=${sq(identity.lifecycleEpoch)}`,
    `AGENT=${sq(identity.agentType)}`,
    '',
    'HYDRA_CLI=$(command -v hydra 2>/dev/null || true)',
    '[ -n "$HYDRA_CLI" ] || HYDRA_CLI="$HOME/.hydra/bin/hydra"',
    '[ -x "$HYDRA_CLI" ] || exit 0',
    '',
    '"$HYDRA_CLI" hooks complete \\',
    '  --worker-id "$WORKER_ID" \\',
    '  --lifecycle-epoch "$LIFECYCLE_EPOCH" \\',
    '  --agent "$AGENT" \\',
    '  --json >/dev/null 2>&1 || true',
    '',
  ].join('\n');
}

function buildPowerShellScript(identity: CompletionHookScriptIdentity): string {
  const psq = (value: string) => `'${value.replace(/'/g, "''")}'`;
  return [
    '# Auto-generated by Hydra: structured worker completion signal.',
    "$ErrorActionPreference = 'SilentlyContinue'",
    `$WORKER_ID = ${psq(String(identity.workerId))}`,
    `$LIFECYCLE_EPOCH = ${psq(identity.lifecycleEpoch)}`,
    `$AGENT = ${psq(identity.agentType)}`,
    '$PAYLOAD = [Console]::In.ReadToEnd()',
    '',
    '$hydra = Get-Command hydra -ErrorAction SilentlyContinue',
    '$hydraPath = if ($hydra) { $hydra.Source } else { $null }',
    'if (-not $hydraPath) {',
    "  foreach ($candidate in @((Join-Path $HOME '.hydra\\bin\\hydra.cmd'), (Join-Path $HOME '.hydra\\bin\\hydra.ps1'), (Join-Path $HOME '.hydra\\bin\\hydra'))) {",
    '    if (Test-Path -LiteralPath $candidate) { $hydraPath = $candidate; break }',
    '  }',
    '}',
    'if ($hydraPath) {',
    '  $PAYLOAD | & $hydraPath hooks complete --worker-id $WORKER_ID --lifecycle-epoch $LIFECYCLE_EPOCH --agent $AGENT --json *> $null',
    '}',
    'exit 0',
    '',
  ].join('\r\n');
}

function validateIdentity(identity: CompletionHookScriptIdentity): void {
  if (!Number.isSafeInteger(identity.workerId) || identity.workerId <= 0) {
    throw new Error('Completion hook workerId must be a positive safe integer');
  }
  validateRequiredString(identity.lifecycleEpoch, 'lifecycleEpoch');
  validateRequiredString(identity.agentType, 'agentType');
}

function validateRequiredString(value: unknown, field: string): asserts value is string {
  if (typeof value !== 'string' || !value.trim() || value.length > 500) {
    throw new Error(`Completion hook ${field} must be a non-empty string of at most 500 characters`);
  }
}

function scriptExtension(platform: typeof process.platform): 'ps1' | 'sh' {
  return platform === 'win32' ? 'ps1' : 'sh';
}

function readFile(filePath: string): string | undefined {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch {
    return undefined;
  }
}
