/**
 * Smoke test: Windows structured completion hook shape.
 *
 * The generated PowerShell is inspected on every platform. Actual PowerShell
 * execution remains a packaged-Windows validation concern.
 */

import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { buildAgentCompletionHookCommand } from '../core/agentHookAdapter';
import {
  buildCompletionHookScript,
  getCompletionHookScriptPath,
} from '../core/completionHookScript';

async function main(): Promise<void> {
  const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'hydra-smoke-completion-ps-'));
  const previous = {
    HOME: process.env.HOME,
    HYDRA_HOME: process.env.HYDRA_HOME,
    HYDRA_CONFIG_PATH: process.env.HYDRA_CONFIG_PATH,
  };
  process.env.HOME = tempHome;
  process.env.HYDRA_HOME = path.join(tempHome, '.hydra');
  process.env.HYDRA_CONFIG_PATH = path.join(process.env.HYDRA_HOME, 'config.json');

  try {
    const identity = {
      workerId: 7,
      lifecycleEpoch: "epoch-with-'quote'",
      agentType: "codex-with-'quote'",
    };
    const script = buildCompletionHookScript(identity, 'win32');

    assert.doesNotMatch(script, /^#!\/bin\/sh/);
    assert.match(script, /Auto-generated by Hydra/);
    assert.match(script, /ErrorActionPreference/);
    assert.match(script, /\$WORKER_ID = '7'/);
    assert.match(script, /\$LIFECYCLE_EPOCH = 'epoch-with-''quote'''/);
    assert.match(script, /\$AGENT = 'codex-with-''quote'''/);
    assert.match(script, /\[Console\]::In\.ReadToEnd\(\)/);
    assert.match(script, /hooks complete/);
    assert.match(script, /--worker-id \$WORKER_ID/);
    assert.match(script, /--lifecycle-epoch \$LIFECYCLE_EPOCH/);
    assert.ok(script.includes('\r\n'), 'PowerShell script should use CRLF line endings');

    for (const banned of [
      '#!/bin/sh',
      '.pending',
      'notify create',
      'load-buffer',
      'paste-buffer',
      'send-keys',
      'HYDRA_TMUX_SOCKET',
      '$COPILOT',
      '$SESSION',
      '$BRANCH',
      '$WORKDIR',
      'mktemp',
      'trap ',
      'case ',
    ]) {
      assert.equal(script.includes(banned), false, `PowerShell signal script must not contain ${banned}`);
    }

    const fakeScriptPath = path.join(process.env.HYDRA_HOME, 'hooks', 'completion-worker-7.ps1');
    const claudeCmd = buildAgentCompletionHookCommand(fakeScriptPath, 'claude', undefined, 'win32');
    const codexCmd = buildAgentCompletionHookCommand(fakeScriptPath, 'codex', undefined, 'win32');
    const geminiCmd = buildAgentCompletionHookCommand(fakeScriptPath, 'gemini', undefined, 'win32');
    for (const command of [claudeCmd, codexCmd, geminiCmd]) {
      assert.match(command, /^powershell\.exe -NoProfile -ExecutionPolicy Bypass -File /);
      assert.ok(command.includes(path.basename(fakeScriptPath)));
      assert.equal(command.includes('>/dev/null'), false);
      assert.equal(command.startsWith('sh '), false);
    }
    assert.equal(claudeCmd.includes('echo {}'), false);
    assert.ok(codexCmd.endsWith('>NUL & echo {}'));
    assert.ok(geminiCmd.endsWith('>NUL & echo {}'));

    const platformPath = getCompletionHookScriptPath(7);
    const expectedExt = process.platform === 'win32' ? 'ps1' : 'sh';
    assert.ok(platformPath.endsWith(`completion-worker-7.${expectedExt}`));

    const { SessionManager } = await import('../core/sessionManager');
    const { TmuxBackendCore } = await import('../core/tmux');
    const manager = new SessionManager(new TmuxBackendCore()) as unknown as {
      injectCompletionHook(
        workdir: string,
        agent: string,
        info: { sessionName: string; workerId: number; lifecycleEpoch: string; agentType: string },
      ): boolean;
      withCodexCompletionHookOverrides(command: string, roots: string[], scriptPath: string): string;
    };
    const workdir = path.join(tempHome, 'worktree');
    fs.mkdirSync(workdir, { recursive: true });
    assert.equal(manager.injectCompletionHook(workdir, 'codex', {
      sessionName: 'mutable-worker-route',
      workerId: 7,
      lifecycleEpoch: 'legacy-worker-7',
      agentType: 'codex',
    }), true);
    assert.equal(fs.existsSync(platformPath), true);

    const override = manager.withCodexCompletionHookOverrides('codex', ['/tmp/repo'], platformPath);
    assert.ok(override.includes(platformPath.replace(/\\/g, '\\\\')) || override.includes(platformPath));
    assert.equal(override.includes('notify-mutable-worker-route'), false);

    console.log('notifyHookWindowsSmoke: ok');
  } finally {
    for (const [key, value] of Object.entries(previous)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
    fs.rmSync(tempHome, { recursive: true, force: true });
  }
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.stack || error.message : String(error));
  process.exitCode = 1;
});
