/**
 * Smoke for the Windows notify-hook variants (issue #225 §3).
 *
 * Calls buildNotifyScriptPowerShell / buildNotifyHookCommandPowerShell on
 * SessionManager directly so the assertions run on any host platform — the
 * existing completionHookSmoke continues to cover the POSIX .sh path on
 * macOS/Linux CI. We can't actually execute the .ps1 here (no powershell.exe
 * on macOS CI, no psmux), so this smoke verifies the produced shape: extension
 * choice, control-flow shape, no POSIX-only constructs, and the agent JSON
 * contracts.
 */

import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

async function main(): Promise<void> {
  const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'hydra-smoke-notify-ps-'));
  const origHome = process.env.HOME;
  const origHydraHome = process.env.HYDRA_HOME;
  const origHydraConfigPath = process.env.HYDRA_CONFIG_PATH;
  process.env.HOME = tempHome;

  const hydraDir = path.join(tempHome, '.hydra');
  process.env.HYDRA_HOME = hydraDir;
  process.env.HYDRA_CONFIG_PATH = path.join(hydraDir, 'config.json');
  fs.mkdirSync(hydraDir, { recursive: true });
  fs.writeFileSync(
    path.join(hydraDir, 'sessions.json'),
    JSON.stringify({ copilots: {}, workers: {}, nextWorkerId: 1, updatedAt: new Date().toISOString() }),
  );

  try {
    const { SessionManager } = await import('../core/sessionManager');
    const { TmuxBackendCore } = await import('../core/tmux');

    const backend = new TmuxBackendCore();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sm = new SessionManager(backend) as any;

    const repoInfo = {
      copilotSessionName: 'repo_my-copilot',
      sessionName: 'repo_feat-auth',
      workerId: 7,
      displayName: "name with 'quote'",
      source: 'repo',
      branch: 'feat/auth',
      workdir: "C:\\Users\\me\\worktree with 'quote'",
    };
    const taskInfo = { ...repoInfo, source: 'directory', branch: '' };

    const ps1Repo: string = sm['buildNotifyScriptPowerShell'](repoInfo);
    const ps1Task: string = sm['buildNotifyScriptPowerShell'](taskInfo);

    // ── Header / shell signal ──
    assert.doesNotMatch(ps1Repo, /^#!\/bin\/sh/, 'PowerShell script must not start with a sh shebang');
    assert.match(ps1Repo, /Auto-generated by Hydra/, 'Comment header must be preserved');
    assert.match(ps1Repo, /ErrorActionPreference/, 'Must set PS error preference');

    // ── Single-quoted variable assignments survive embedded apostrophes ──
    assert.match(
      ps1Repo,
      /\$NAME = 'name with ''quote'''/,
      "Single-quoted PS literal must double internal single quotes",
    );
    assert.match(
      ps1Repo,
      /\$WORKDIR = 'C:\\Users\\me\\worktree with ''quote'''/,
      "Workdir literal must preserve backslashes and double single quotes",
    );

    // ── Control flow uses PowerShell, not POSIX ──
    assert.match(ps1Repo, /Test-Path -LiteralPath \$PENDING/);
    assert.match(ps1Repo, /New-Item -ItemType Directory -Path \$LOCKDIR/);
    assert.match(ps1Repo, /Remove-Item -LiteralPath \$LOCKDIR/);
    assert.match(ps1Repo, /\$LASTEXITCODE/);
    assert.match(ps1Repo, /Start-Sleep -Milliseconds 100/);
    assert.match(ps1Repo, /load-buffer -b \$b \$f/);
    assert.match(ps1Repo, /paste-buffer -b \$b -t \$COPILOT -d/);
    assert.match(ps1Repo, /send-keys -t \$COPILOT Enter/);

    // ── No POSIX-only tokens that cmd.exe / pwsh would choke on ──
    for (const banned of ['#!/bin/sh', 'mktemp', 'trap ', 'case ', ' esac', 'rm -rf', '$(mktemp)']) {
      assert.ok(!ps1Repo.includes(banned), `PS script must not contain POSIX-only token: ${banned}`);
    }

    // ── psmux, not tmux, as the multiplexer binary ──
    assert.match(ps1Repo, /\$tmuxBin = 'psmux'/);

    // ── HYDRA_TMUX_SOCKET path-vs-name detection is Windows-aware ──
    // It must accept both POSIX-absolute (/a/b) AND Windows-absolute (C:\a\b).
    assert.match(ps1Repo, /\[A-Za-z\]:\[\\\\\/\]/);

    // ── CRLF line endings (Windows-friendly; some editors require it) ──
    assert.ok(ps1Repo.includes('\r\n'), 'PS script should use CRLF line endings');

    // ── Source-dependent message text ──
    assert.match(ps1Repo, /Worker #\$WORKER_ID/);
    assert.match(ps1Repo, /Branch: \$BRANCH/);
    assert.match(ps1Task, /Task worker #\$WORKER_ID/);
    assert.match(ps1Task, /Workdir: \$WORKDIR/);

    // ── Hook command shape for each agent ──
    const fakeScriptPath = path.join(hydraDir, 'hooks', 'notify-x.ps1');
    const claudeCmd: string = sm['buildNotifyHookCommandPowerShell'](fakeScriptPath, 'claude');
    const codexCmd: string = sm['buildNotifyHookCommandPowerShell'](fakeScriptPath, 'codex');
    const geminiCmd: string = sm['buildNotifyHookCommandPowerShell'](fakeScriptPath, 'gemini');

    for (const cmd of [claudeCmd, codexCmd, geminiCmd]) {
      assert.match(cmd, /^powershell\.exe -NoProfile -ExecutionPolicy Bypass -File /);
      assert.ok(cmd.includes(path.basename(fakeScriptPath)), 'Hook command must reference the script path');
      assert.ok(!cmd.includes('>/dev/null'), 'Hook command must not use POSIX /dev/null');
      assert.ok(!cmd.startsWith('sh '), 'Hook command must not invoke sh on Windows');
    }

    // Claude: plain script invocation, no JSON tail.
    assert.ok(!claudeCmd.includes('echo {}'), 'Claude hook must not append JSON tail');
    assert.ok(!claudeCmd.includes('>NUL'), 'Claude hook must not redirect to NUL');

    // Codex / Gemini: append `>NUL & echo {}` so the agent sees `{}` on stdout.
    for (const cmd of [codexCmd, geminiCmd]) {
      assert.ok(cmd.endsWith('>NUL & echo {}'), `Codex/Gemini hook must emit {} via cmd: got ${cmd}`);
    }

    // ── injectCompletionHook writes .ps1 on Windows, .sh on POSIX ──
    const fakeWorktree = path.join(tempHome, 'worktree');
    fs.mkdirSync(fakeWorktree, { recursive: true });
    sm['injectCompletionHook'](fakeWorktree, 'claude', repoInfo);
    const expectedExt = process.platform === 'win32' ? 'ps1' : 'sh';
    const writtenPath = path.join(hydraDir, 'hooks', `notify-${repoInfo.sessionName}.${expectedExt}`);
    assert.ok(
      fs.existsSync(writtenPath),
      `injectCompletionHook must write notify-*.${expectedExt} on platform ${process.platform}`,
    );

    // ── getNotifyScriptPath is the single source of truth ──
    // Both the file written by injectCompletionHook AND the path embedded in
    // Codex's inline hook override must come from the same helper. Otherwise
    // Windows codex workers reference a non-existent .sh while the .ps1 lives
    // on disk. See issue #225 §3 (codex review round 1).
    const helperPath = sm['getNotifyScriptPath'](repoInfo.sessionName);
    assert.equal(helperPath, writtenPath, 'getNotifyScriptPath must match injectCompletionHook output');
    assert.ok(
      helperPath.endsWith(`.${expectedExt}`),
      `getNotifyScriptPath must end with .${expectedExt} on ${process.platform}`,
    );

    // ── Codex inline override embeds the helper path ──
    const codexOverride: string = sm['withCodexCompletionHookOverrides'](
      'codex',
      ['/tmp/repo'],
      helperPath,
    );
    assert.ok(
      codexOverride.includes(helperPath.replace(/\\/g, '\\\\'))
        || codexOverride.includes(helperPath),
      `Codex override must embed the platform-correct script path: ${codexOverride}`,
    );
    if (process.platform === 'win32') {
      assert.ok(
        !codexOverride.includes(`notify-${repoInfo.sessionName}.sh`),
        `Codex override must NOT reference .sh on Windows: ${codexOverride}`,
      );
    }

    console.log('notifyHookWindowsSmoke: ok');
  } finally {
    if (origHome) process.env.HOME = origHome;
    else delete process.env.HOME;
    if (origHydraHome) process.env.HYDRA_HOME = origHydraHome;
    else delete process.env.HYDRA_HOME;
    if (origHydraConfigPath) process.env.HYDRA_CONFIG_PATH = origHydraConfigPath;
    else delete process.env.HYDRA_CONFIG_PATH;
    fs.rmSync(tempHome, { recursive: true, force: true });
  }
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.stack || error.message : String(error));
  process.exitCode = 1;
});
